### PR TITLE
Fixed CVAT annotation view restoring

### LINKED ISSUE #5133: Cannot restore annotation view when it fails
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Throw UI react rendering error (any way)
1. Try to press ``restore`` button
1. Restore fails
1.

example

### Your Environment

- Git hash commit (`git log -1`): 3aca9bce511
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #5133 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
@klakhov  Could you take a look at this?

File: cvat-ui/src/actions/boundaries-actions.ts [hunk 1]
```diff
@@ -55,9 +64,23 @@ export function resetAfterErrorAsync(): ThunkAction {
...
+                    colors,
+                    [],
+                    frameData,
+                    minZ,
+                    maxZ,
+                ));
             } else {
-                dispatch(boundariesActions.resetAfterError(null, [], 0, null, 0, 0, []));
+                dispatch(boundariesActions.resetAfterError(
+                    null, [], null, 0, '', false, [], [], null, 0, 0,
```
Comment (klakhov) [inline cvat-ui/src/actions/boundaries-actions.ts:82]: Why not to use default params for `resetAfterError` action instead of specifying lots of inconvinient default values like null, 0, false etc.?

Comment (bsekachev) [reply cvat-ui/src/actions/boundaries-actions.ts]: I looked at the code, no need to have ``else`` branch if job is ``undefined`` because this code can not be called in this case.

**Review by klakhov — APPROVED** [review]
