### PR TITLE
Receive value for 'Reset zoom' option from settings saved by user

### LINKED ISSUE #4289: Reset Zoom Setting resets between jobs
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
I expect that I have to disable the zoom resetting once and it stays like this for all jobs I am working on.

### Current Behaviour
I can disable the resetting of the zoom between frames in the player settings. However after I switch to another job/task. The setting is reset. This resetting behavior does not occur for other player settings like the Smooth Image setting.

### Steps to Reproduce (for bugs)
1. go to job and change the setting
2. go to another job and see that the setting was not persistent

### Context
It's just a bit annoying that I have to change the setting everytime I start a new job.

### Your Environment
- Git hash commit (`git log -1`): 6c96891f

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #4289

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Review by klakhov — APPROVED** [review]

File: tests/cypress/e2e/actions_tasks/case_68_saving_settings_local_storage.js [hunk 1]
```diff
@@ -31,15 +60,13 @@ context('Saving setting to local storage.', () => {
...
-            cy.saveSettings();
-            cy.get('.cvat-notification-notice-save-settings-success')
-                .should('exist')
-                .find('[data-icon="close"]')
-                .click();
-            cy.closeSettings();
+            setupAndSaveSettings(true);
             cy.reload();
             testCheckedSettings(true);
+
```
Comment (bsekachev) [inline tests/cypress/e2e/actions_tasks/case_68_saving_settings_local_storage.js:66]:
```suggestion
```
