### PR TITLE
Fixed switching from organization to sandbox while getting a resource

### LINKED ISSUE #6390: Incorrect getting a task out of organization when in organization
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Switch context to any organization
1. Open a task page which is out of organization
1. Job list is emptry (request does not return any jobs)
1. Opening /tasks/<id>/jobs/<id> leads to an error also

### Expected Behaviour
Organization probably should be switched off..?

### Current Behaviour
The issue described abovce

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolves #6390 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] ~~I have updated the documentation accordingly~~
- [ ] ~~I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by klakhov** [comment]
@bsekachev Could you look on this?

File: cvat-core/src/server-proxy.ts [hunk 1]
```diff
@@ -279,9 +279,12 @@ Axios.interceptors.request.use((reqConfig) => {
 });
 
 Axios.interceptors.response.use((response) => {
-    if (isResourceURL(response.config.url)) {
-        const newOrg = response.data.organization;
-        if (newOrg && config.organization.organizationID !== newOrg) {
+    if (isResourceURL(response.config.url) &&
+        response.data &&
+        'organization' in response.data
```
Comment (bsekachev) [inline cvat-core/src/server-proxy.ts:284]:
```suggestion
         'organization' in (response.data || {})
```

File: cvat-ui/src/components/watchers/organization-watcher.tsx [hunk 2]
```diff
@@ -13,7 +13,13 @@ function OrganizationWatcher(): JSX.Element {
     const organizationList = useSelector((state: CombinedState) => state.organizations.list);
 
     useEffect(() => {
-        core.config.onOrganizationChange = (newOrgId: number) => {
+        core.config.onOrganizationChange = (newOrgId: number | null) => {
+            if (newOrgId === null) {
+                localStorage.removeItem('currentOrganization');
+                window.location.reload();
+                return;
```
Comment (bsekachev) [inline cvat-ui/src/components/watchers/organization-watcher.tsx:20]: Can we rewrite with ``else`` and keep only one ``window.location.reload();``?

**Review by bsekachev — APPROVED** [review]
