### PR TITLE
Fixed fail for masks & skeletons with centered text

### LINKED ISSUE #6743: Activating a mask object with centered-text alignment causes error
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Enable centered aligned text
image
2. Hover a mask
image

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #6743

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: cvat-canvas/src/typescript/canvasView.ts [hunk 1]
```diff
@@ -2569,11 +2574,13 @@ export class CanvasViewImpl implements CanvasView, Listener {
         if (textPosition === 'center') {
             let cx = 0;
             let cy = 0;
-            if (shape.type === 'rect') {
+            if (['rect', 'image'].includes(shape.type)) {
                 // for rectangle finding a center is simple
```
Comment (klakhov) [inline cvat-canvas/src/typescript/canvasView.ts:2578]:
```suggestion
                // for rectangle/mask finding a center is simple
```

File: cvat-canvas/src/typescript/canvasView.ts [hunk 2]
```diff
@@ -2569,11 +2574,13 @@ export class CanvasViewImpl implements CanvasView, Listener {
...
-            if (shape.type === 'rect') {
-                // for rectangle finding a center is simple
+            if (['rect', 'image'].includes(shape.type)) {
+                // for rectangle/mask finding a center is simple
                 cx = +shape.attr('x') + +shape.attr('width') / 2;
                 cy = +shape.attr('y') + +shape.attr('height') / 2;
-            } else if (shape.type === 'ellipse') {
+            } else if (shape.type === 'g') {
+                ({ cx, cy } = shape.bbox());
+            } else if (['ellipse'].includes(shape.type)) {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/canvasView.ts:2583]:
```suggestion
            } else if (shape.type === 'ellipse') {
```

**Review by klakhov — APPROVED** [review]
