### PR TITLE
Fixed removing job assignee

### LINKED ISSUE #6700: Remove assignee from job
Hi!
How do I remove a user from a job via the UI? I can only reassign to another user, but I can't completely delete it. It turns out to be deleted only through the admin panel.

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolves #6700 
Fix + tests

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the documentation accordingly~~
- [x] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: tests/cypress/e2e/actions_users/registration_involved/case_4_assign_task_job_users.js [hunk 1]
```diff
@@ -140,6 +141,7 @@ context('Multiple users. Assign task, job. Deactivating users.', () => {
         it('First user login and assign the job to the third user. Logout', () => {
             cy.login();
             cy.openTask(taskName);
+            cy.assignJobToUser(0, '');
```
Comment (bsekachev) [inline tests/cypress/e2e/actions_users/registration_involved/case_4_assign_task_job_users.js:144]: Maybe better to pass null?

**Review by bsekachev — APPROVED** [review]
