### PR TITLE
Fixed SAM plugin (403 code for workers in organizations)

### LINKED ISSUE #6221: Interaction error occurred Error: Exception in plugin Segmeny Anything: Error: Request failed with status code 403.
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. installed cvat 2.4.4 in aws g5.2xlarge instance 
1. created an organization 
1. created a task
1. invited a worker
2. assigned a job for the worker
3. when the worker using hrnet model, he is getting Error as below
Interaction error occurred
Error: Exception in plugin Segmeny Anything: Error: Request failed with status code 403. {"detail":"You do not have permission to perform this action."}.
4 when i assign the worker to a task he is getting no errors

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #6221

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: cvat-ui/plugins/sam_plugin/src/ts/index.tsx [hunk 1]
```diff
@@ -125,6 +134,20 @@ const samPlugin: SAMPlugin = {
     name: 'Segmeny Anything',
```
Comment (kirill-sizov) [inline cvat-ui/plugins/sam_plugin/src/ts/index.tsx:134]:
```suggestion
    name: 'Segment Anything',
```

**Review by kirill-sizov — APPROVED** [review]

**Comment by Keramblock** [comment]
Hi, you just broke develop, could you please fix it?

**Comment by bsekachev** [comment]
@Keramblock 
Could you please clarify what exactly was broken?
