### PR TITLE
[GSoC2024] Add tooltip to long project card name

### LINKED ISSUE #6874: Create pop up containing entire task name when hovering over a task in both project and task list CVAT UI
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create a long task name (over 75 characters) and notice how it gets cut off in task page view

### Expected Behaviour

If you hover your cursor over task name in the task list or inside project a pop up will appear showing full name of task. If there is a long task name it can be hard to read the tasks quickly

### Current Behaviour

Doesn't show entire character length of task name for particularly long names

### Possible Solution

Create a pop up window when hovering over name, particularly if the name is long. For example, my current tasks names are roughly ~75 characters 

### Context

I typically name my batches the name of the .bag file they originated from and then ending in `batch_x`. sometimes when my log names are long it can be difficult to quickly read the batch number when looking through task list

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by syedbarimanjan**
## Motivation and context
Fixes #6874 I added a tooltip component to the name of the project and task card. When someone hovers over the name it will display the name in a tooltip above it.
Screenshot from 2024-03-04 20-24-42
Screenshot from 2024-03-05 00-12-35

### How has this been tested?
On all ui breakpoints.

### Checklist
- [x] I submit my changes into the `develop` branch
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: cvat-ui/src/components/projects-page/project-item.tsx [hunk 1]
```diff
@@ -85,7 +86,13 @@ export default function ProjectItemComponent(props: Props): JSX.Element {
                 className='cvat-projects-project-item-card'
             >
                 <Meta
-                    title={(
+                    title={instance.name.length >= 21 ? (
```
Comment (bsekachev) [inline cvat-ui/src/components/projects-page/project-item.tsx:89]: I am not sure we really need to rely on the name length, because different number of characters may be placed on the item depends on the screen resolution, do not you think so?

Comment (syedbarimanjan) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: If we add the tooltip by default then if the name is small it will confuse the user as to why is there a tooltip when they can view the name already 
Screenshot from 2024-03-05 12-41-38
and as to why i am checking it against the number 21 is because when tested with differnt ui breakpoints this was the smallest length at which the name was cut off below this number the full name is visible.

Comment (syedbarimanjan) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: > I am not sure we really need to rely on the name length, because different number of characters may be placed on the item depends on the screen resolution, do not you think so?

If we add the tooltip by default then if the name is small it will confuse the user as to why is there a tooltip when they can view the name already 
Screenshot from 2024-03-05 12-41-38
and as to why is the number 21 it is because when tested with differnt ui breakpoints this was the smallest length at which the name was cut off below this number the full name is visible.

Comment (syedbarimanjan) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: > I am not sure we really need to rely on the name length, because different number of characters may be placed on the item depends on the screen resolution, do not you think so?

@bsekachev just a reminder to review this.

Comment (bsekachev) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: image

Unfortunately, as I told it will not work with just relying on count of characters. That is a regular 1920x1080px with scaling 100%.

Comment (bsekachev) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: Reversed case when name of 19 characters is not visible:
image

Comment (bsekachev) [reply cvat-ui/src/components/projects-page/project-item.tsx:89]: And remember, that width of characters is not the same
image

Comment (syedbarimanjan) [reply cvat-ui/src/components/projects-page/project-item.tsx]: > And remember, that width of characters is not the same image

Oh you were talking about this, then there isnt much we can do. I will change it so that the tooltip is shown by default.

Comment (bsekachev) [reply cvat-ui/src/components/projects-page/project-item.tsx]: > then there isnt much we can do

I believe, we can.

Comment (bsekachev) [reply cvat-ui/src/components/projects-page/project-item.tsx]: e.g. https://stackoverflow.com/questions/61124992/is-it-possible-to-show-an-ant-design-tooltip-conditionally-only-when-the-content

Comment (syedbarimanjan) [reply cvat-ui/src/components/projects-page/project-item.tsx]: > e.g. https://stackoverflow.com/questions/61124992/is-it-possible-to-show-an-ant-design-tooltip-conditionally-only-when-the-content

this saves us alot of time +1 for antdesign. I implemented it.

File: cvat-ui/src/components/tasks-page/task-item.tsx [hunk 2]
```diff
@@ -121,10 +122,21 @@ class TaskItemComponent extends React.PureComponent<TaskItemProps & RouteCompone
 
         return (
             <Col span={10} className='cvat-task-item-description'>
-                <Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
-                <Text strong className='cvat-item-task-name'>
-                    {name}
-                </Text>
+                {taskInstance.name.length > 70 ? (
```
Comment (bsekachev) [inline cvat-ui/src/components/tasks-page/task-item.tsx:125]: Perhaps we do not need that condition now. Is not it? 
We may use the same scheme with antd ellipse.

**Comment by bsekachev** [comment]
Also it would be great to have the same approach we should use now for Cloud Storages and Models page. 
Now the names are not visible
image
image

File: cvat-ui/src/components/tasks-page/task-item.tsx (hunk 2 above)
Comment (syedbarimanjan) [reply cvat-ui/src/components/tasks-page/task-item.tsx]: > Perhaps we do not need that condition now. Is not it? We may use the same scheme with antd ellipse.

Yes we dont need it but by using ellipse the name will be in two lines I have applied the changes you should look at it.

**Comment by syedbarimanjan** [comment]
> Also it would be great to have the same approach we should use now for Cloud Storages and Models page. Now the names are not visible image image

I have implemented the changes.

**Comment by bsekachev** [comment]
May you please add changelog fragment?

`scriv create --edit`, and add description with PR link. Description is something line: 

```
Added:
    - Tooltips for long resources names (projects, tasks, cloud storages, and models)
```

File: changelog.d/20240313_200940_syedbarimnajan_long_cardname_tooltip.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Added
+
+- Tooltips for long card names (projects, tasks, cloud storages, and models)
+  (<https://github.com/opencv/cvat/pull/7550>)
```
Comment (bsekachev) [inline changelog.d/20240313_200940_syedbarimnajan_long_cardname_tooltip.md:4]:
```suggestion
### Added

- Tooltips for long names on cards (projects, tasks, cloud storages, and models)
  (<https://github.com/opencv/cvat/pull/7550>)
```

File: cvat-ui/src/components/tasks-page/task-item.tsx [hunk 4]
```diff
@@ -116,16 +116,16 @@ class TaskItemComponent extends React.PureComponent<TaskItemProps & RouteCompone
...
-                </Text>
-                <br />
+                <Paragraph
+                    ellipsis={{ rows: 2, tooltip: taskInstance.name }}
+                >
+                    <Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
+                    <Text strong className='cvat-item-task-name'>
+                        {taskInstance.name}
+                    </Text>
+                </Paragraph>
```
Comment (bsekachev) [inline cvat-ui/src/components/tasks-page/task-item.tsx:128]: Perhaps it should be <Text>, not <Paragraph>.

Like:

```
<Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
<Text ellipsis={{ rows: 1, tooltip: taskInstance.name }} strong className='cvat-item-task-name'>
    {taskInstance.name}
</Text>
```

Because now we have only one line for a name. And in this case we do not need chaaning styles above.

Comment (syedbarimanjan) [reply cvat-ui/src/components/tasks-page/task-item.tsx:128]: > That should be good enough.
> 
> ```
> <>
>     <Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
>     <Text ellipsis={{ tooltip: taskInstance.name }} strong className='cvat-item-task-name'>
>         {taskInstance.name}
>     </Text>
> </>
> ```
> 
> General recommendation is to be consistent here. If in three of four cases we do not show tooltip on hovering ID, then probably in the fourth case we should behave the same.

In one of two cases we are showing the tooltip upon hovering on id. The other cards dont have id in them just the cloud storage and task card have id.

We are choosing to not show the tooltip upon hovering on id?

Comment (bsekachev) [reply cvat-ui/src/components/tasks-page/task-item.tsx:128]: Fair enough. Let me left this decision up to you, then.

File: cvat-ui/src/components/tasks-page/styles.scss [hunk 5]
```diff
@@ -137,6 +137,10 @@
     word-break: break-all;
     max-height: 100%;
     overflow: hidden;
+
+    > div {
+        margin: 0;
+    }
```
Comment (bsekachev) [inline cvat-ui/src/components/tasks-page/styles.scss:143]:
```suggestion
```

File: cvat-ui/src/components/tasks-page/task-item.tsx [hunk 6]
```diff
@@ -116,16 +116,14 @@ class TaskItemComponent extends React.PureComponent<TaskItemProps & RouteCompone
...
-                <Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
-                <Text strong className='cvat-item-task-name'>
-                    {name}
+                <Text ellipsis={{ tooltip: taskInstance.name }}>
+                    <Text strong type='secondary' className='cvat-item-task-id'>{`#${id}: `}</Text>
+                    <Text strong className='cvat-item-task-name'>
+                        {taskInstance.name}
+                    </Text>
                 </Text>
-                <br />
```
Comment (bsekachev) [inline cvat-ui/src/components/tasks-page/task-item.tsx:128]: 👀👀👀

image

**Comment by bsekachev** [comment]
ESLint found one error in current changes:

```
/home/runner/work/cvat/cvat/cvat-ui/src/components/tasks-page/task-item.tsx
Error:   10:8  error  'Paragraph' is defined but never used  @typescript-eslint/no-unused-vars
```

**Comment by bsekachev** [comment]
Thank you for active contributing to the project

**Review by bsekachev — APPROVED** [review]
