### PR TITLE
[WIP] Fixed openvino installation

### LINKED ISSUE #392: Support OpenVINO 2019R*
$sudo docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml build

fails with error below: (additionally to this I cannot find install_cv_sdk_dependencies.sh in l_openvino_toolkit_p_2019.1.094.tgz)

/tmp/components/openvino/install.sh: line 26: ./install_cv_sdk_dependencies.sh: No such file or directory
/tmp/components/openvino/install.sh: line 34: /opt/intel/computer_vision_sdk/bin/setupvars.sh: No such file or directory
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh;     fi' returned a non-zero code: 1

### PR DESCRIPTION
**Pull request by bsekachev**
Resolved #392

### CODE REVIEW

File: components/openvino/install.sh [hunk 1]
```diff
@@ -23,12 +23,18 @@ tar -xzf `ls | grep "openvino_toolkit"`
 cd `ls -d */ | grep "openvino_toolkit"`
 
 apt-get update && apt-get install -y sudo cpio && \
- ./install_cv_sdk_dependencies.sh && SUDO_FORCE_REMOVE=yes apt-get remove -y sudo
+ if [ -f "install_cv_sdk_dependencies.sh" ]; then ./install_cv_sdk_dependencies.sh; \
+ else echo ./install_openvino_dependencies.sh; fi && SUDO_FORCE_REMOVE=yes apt-get remove -y sudo
```
Comment (alalek) [inline components/openvino/install.sh]: echo?

Comment (bsekachev) [reply components/openvino/install.sh]: @alalek Yes, I have already found the issue.

**Comment by fadeevla** [comment]
I had an issue with missing libgtk-x11-2.0.so.0 during cv2 import which was solved after adding libgtk2.0-0 to Dockerfile. otherwise it works for me finally. issue details below:
File "/home/django/cvat/apps/reid/reid.py", line 7, in <module>
    import cv2
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
