### PR TITLE
SDK alpha 1 release

### LINKED ISSUE #3716: Provide CLI as own package
### My actions before raising this issue
- [ x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x ] Searched [past issues](/issues)

### Expected Behaviour

I'd like to be able to `pip install cvat-cli`.

### Current Behaviour

`ERROR: No matching distribution found for cvat-cli` :(
### Possible Solution

Extract the [utils/cli](/openvinotoolkit/cvat/tree/develop/utils/cli) directory to its own repository named `cvat-cli`, make this pypi conform so that it can be packaged and easily worked with from within python code and include it as a git submodule here in the cvat repository

### Context

We have a CVAT instance for labeling data. We now want to write code that automatically downloads all new labelled data. Right now, we've implemented custom functions for this, but it would be much easier if we could just import the cli and use that instead.

### LINKED ISSUE #4637: Python SDK Support
I want to interact with CVAT in local server and docker with CMD using python script
is there a stable python API to create and upload and download data from CVAT

### LINKED ISSUE #4859: Errors during installation of cvat-cli [cvat-sdk==2.0]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Following the documentation Manual/Advanced/CLI to install cvat-cli:
`pip install 'git+https://github.com/cvat-ai/cvat#subdirectory=cvat-cli'`

### Current Behaviour
`pip install 'git+https://github.com/cvat-ai/cvat#subdirectory=cvat-cli'`
Returns:
`
ERROR: Could not find a version that satisfies the requirement cvat-sdk==2.0 (from cvat-cli) (from versions: none)
ERROR: No matching distribution found for cvat-sdk==2.0
`
After that cvat-cli is not installed.

### Steps to Reproduce (for bugs)

1. Create virual env and activate it
1.`pip install 'git+https://github.com/cvat-ai/cvat#subdirectory=cvat-cli'`

### Your Environment

- Git hash commit (`git log -1`):
- Python version (`python --version`): 3.8.10
- Pip versione (`pip --version`): pip 20.0.2
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Uubuntu 18.04 LTS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Pip execution logs:</summary>
    <pre>
pip install 'git+https://github.com/cvat-ai/cvat#subdirectory=cvat-cli'
Collecting git+https://github.com/cvat-ai/cvat#subdirectory=cvat-cli
  Cloning https://github.com/cvat-ai/cvat to /tmp/pip-req-build-1w_wtosj
  Running command git clone -q https://github.com/cvat-ai/cvat /tmp/pip-req-build-1w_wtosj
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Could not find a version that satisfies the requirement cvat-sdk==2.0 (from cvat-cli==0.2) (from versions: none)
ERROR: No matching distribution found for cvat-sdk==2.0 (from cvat-cli==0.2)
   </pre>
   </details>

Issue by @matteobarato

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Closes #3716 
Closes #4637 
Closes #4859

- SDK:
  - Updated package docs
  - Added missing `pillow` dependency
  - Removed generated version file
- CLI:
  - Aligned version number with SDK
  - Updated README: added examples, installation uses package

Examples:
- sdk https://test.pypi.org/project/cvat-sdk/2.0a1.dev1/
- cli https://test.pypi.org/project/cvat-cli/2.0a1/

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: cvat-sdk/gen/generate.sh [hunk 1]
```diff
@@ -8,7 +8,7 @@ set -e
 
 GENERATOR_VERSION="v6.0.1"
 
-VERSION="2.0-alpha"
+VERSION="2.0a1"
```
Comment (nmanovic) [inline cvat-sdk/gen/generate.sh:11]: @zhiltsov-max , it is a known way to version python packages? It looks unusual.

Comment (zhiltsov-max) [reply cvat-sdk/gen/generate.sh:11]: Yes, it is described here: https://peps.python.org/pep-0440/#public-version-identifiers

**Review by nmanovic — APPROVED** [review]
