### PR TITLE
[GSoC2024] fix and refactor import-dataset-modal code (#7428)

### LINKED ISSUE #7428: Wrong filename used when importing from cloud storage after another import
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a task.
2. Export the task's annotations twice: first to the local computer (name it `foobar.zip`), then to a cloud storage (name it `bazquux.zip`).
3. Import the annotations from `foobar.zip`.
4. Import the annotations from the cloud storage, entering `bazquux.zip` as the name.

The last step fails and shows the following error:

> rest_framework.exceptions.NotFound: The file 'foobar.zip' not found on the cloud storage '[redacted]'.

### Expected Behavior

CVAT should import the annotations from `bazquux.zip`.

### Possible Solution

_No response_

### Context

I hit this while testing import-related functionality.

### Environment

```Markdown
Reproducible on commit 27f8aa7ea and also on app.cvat.ai.
```

### PR DESCRIPTION
**Pull request by umangapatel123**
Refactor code to use useReducer instead of useState. Fixes #7428
'file' and 'fileName' in the uploadParams were not set to null after import. To avoid this change the code to set 'file' and 'fileName' to null after importing is done.

### Motivation and context

This change is required to make the code clear. The previous code uses many `useState` to manage the state but this version uses `useReducer` to manage all the states.
In the previous code `file` and `fileName` in the `uploadParams` were not set to null after importing was done but this version set it to null so it can not use the previous file while importing annotation.
it solves issue #7428

### How has this been tested?

The changes have been tested manually. The code was tested using different sequences of annotation uploads. The state of each parameter is tested by logging its state to the console.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~ 
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- ~~[ ] I have increased versions of npm packages if it is necessary~~
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md [hunk 1]
```diff
@@ -0,0 +1,4 @@
+### Fixed
+
+- set `file` and `fileName` to null after import is done and change `useState` to `useReducer`
```
Comment (bsekachev) [inline changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md:3]: We should describe here what it means for a CVAT user, not for developer.

Comment (umangapatel123) [reply changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md]: can you please review now?

File: changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+### Fixed
+
+- Incorrect file name usage in importing annotation via cloud storage
```
Comment (bsekachev) [inline changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md:3]:
```suggestion
- Incorrect file name usage when importing annotations from a cloud storage
```

**Comment by umangapatel123** [comment]
@klakhov can you please review?

File: cvat-ui/src/components/import-dataset/import-dataset-modal.tsx [hunk 3]
```diff
@@ -66,67 +277,71 @@ function ImportDatasetModal(props: StateToProps): JSX.Element {
...
             }
-            setInstanceType(`${type} #${instance.id}`);
+            dispatchReducer(reducerActions.setInstanceType(`${type} #${instance.id}`));
         }
     }, [instance, resource]);
 
     useEffect(() => {
-        setHelpMessage(
+        dispatchReducer(reducerActions.setHelpMessage(
             // eslint-disable-next-line prefer-template
```
Comment (klakhov) [inline cvat-ui/src/components/import-dataset/import-dataset-modal.tsx:341]: I think we can remove this `eslint disable` since the template literals are already used  in the string below

File: cvat-ui/src/components/import-dataset/import-dataset-modal.tsx [hunk 4]
```diff
@@ -57,6 +58,216 @@ interface UploadParams {
...
+        return {
+            ...state,
+            useDefaultSettings: action.payload.useDefaultSettings,
+            uploadParams: {
+                ...state.uploadParams,
+                useDefaultSettings: action.payload.useDefaultSettings,
+                sourceStorage: isDefaultSettings ? {
+                    location: state.defaultStorageLocation,
+                    cloudStorageId: state.defaultStorageCloudId,
+                } as Storage : state.uploadParams.sourceStorage,
```
Comment (klakhov) [inline cvat-ui/src/components/import-dataset/import-dataset-modal.tsx:169]: Lets instantiate default Storage here. Using type cast looks unsafe

**Review by klakhov — COMMENTED** [review]
Could you also check the import cypress test? Its failed [here].(https://github.com/opencv/cvat/actions/runs/8255177378/job/22597458735)
[Tests docs](https://opencv.github.io/cvat/docs/contributing/setup-additional-components/#run-cypress-tests)
From quick look on the failed test I see the wrong notification is shown. Looks like while importing a project locally incorrect `resourse` param is inside `uploadParams`.

File: cvat-ui/src/components/import-dataset/import-dataset-modal.tsx [hunk 5]
```diff
@@ -66,67 +277,71 @@ function ImportDatasetModal(props: StateToProps): JSX.Element {
...
-    const [selectedLoader, setSelectedLoader] = useState<any>(null);
-    const [useDefaultSettings, setUseDefaultSettings] = useState(true);
-    const [defaultStorageLocation, setDefaultStorageLocation] = useState(StorageLocation.LOCAL);
-    const [defaultStorageCloudId, setDefaultStorageCloudId] = useState<number | undefined>(undefined);
-    const [helpMessage, setHelpMessage] = useState('');
-    const [selectedSourceStorageLocation, setSelectedSourceStorageLocation] = useState(StorageLocation.LOCAL);
-    const [uploadParams, setUploadParams] = useState<UploadParams>({
-        convMaskToPoly: true,
+
+    const [state, dispatchReducer] = useReducer(reducer, {
```
Comment (klakhov) [inline cvat-ui/src/components/import-dataset/import-dataset-modal.tsx:281]: Lets use a bit different notation, `dispatch` as local dispatch, and `appDispatch` as main app dispatch

**Comment by umangapatel123** [comment]
@klakhov I've made the changes based on your suggestion and resolved the failing Cypress test. Could you please review it now?

**Comment by umangapatel123** [comment]
@klakhov can you please approve the changes?

**Review by klakhov — APPROVED** [review]

**Comment by klakhov** [comment]
@umangapatel123, Thanks for contribution. 
As you've fixed a bug with importing a dataset, would you mind to contribute a cypress test covering this bug? I belive we need to reproduce the original issue's scenario. You may be familiar with test system already, as it helped to identify a problem in the pr. 
For inspiration, you can look on [project export test](https://github.com/opencv/cvat/blob/develop/tests/cypress/e2e/actions_projects_models/case_103_project_export.js) and tests concerning cloud storages [here](https://github.com/opencv/cvat/blob/develop/tests/cypress/e2e/actions_tasks3/case_114_use_default_task_storage_for_import_export_annotations.js) and [here](https://github.com/opencv/cvat/blob/develop/tests/cypress/e2e/actions_tasks3/case_115_use_custom_storage_for_import_export_annotations.js)

**Comment by umangapatel123** [comment]
Okay, I will do that.

**Comment by klakhov** [comment]
Hi @umangapatel123 , can you share with us your progress with test? Are you still going to contribute?

**Comment by umangapatel123** [comment]
> Hi @umangapatel123 , can you share with us your progress with test? Are you still going to contribute?

I am still working on it. yes, I am contributing. I was busy for some days due to university examinations.
