### PR TITLE
Fixed activation bug with frame switching

### LINKED ISSUE #1611: CVAT new UI: Error when switching to another frame immediately after opening the job
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

N/A
### Current Behaviour

An error occurs if you switch to a large number of frames ahead (by clicking on the slider), approximately 5 seconds after the task is opened.

### Possible Solution

N/A
### Steps to Reproduce (for bugs)

1. Open job
1. Wait ~5 seconds
1. Switch to a another frame (by clicking on the player slider)

### Context

CVAT version
Server: 1.0rc0
Core: 2.0.1
Canvas: 1.1.1
UI: 1.2.0

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 and Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Error message
TypeError
Cannot read property 'objectType' of undefined

TypeError: Cannot read property 'objectType' of undefined
    at ld.activateOnCanvas (.../cvat-ui.min.js:72:1424130)
    at ld.componentDidUpdate (.../cvat-ui.min.js:72:1422014)
    at yl (.../cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (.../cvat-ui.min.js:51:3465)
    at Br (.../cvat-ui.min.js:43:45441)
    at gl (.../cvat-ui.min.js:43:97113)
    at ol (.../cvat-ui.min.js:43:87489)
    at .../cvat-ui.min.js:43:45732
    at t.unstable_runWithPriority (.../cvat-ui.min.js:51:3465)
    at Br (.../cvat-ui.min.js:43:45441)</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

This PR fixed #1611 

### How has this been tested?

Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx [hunk 1]
```diff
@@ -571,7 +571,7 @@ export default class CanvasWrapperComponent extends React.PureComponent<Props> {
                     canvasInstance.fit();
                 }
             }
-            if (activatedState.objectType !== ObjectType.TAG) {
+            if (activatedState && activatedState.objectType !== ObjectType.TAG) {
```
Comment (bsekachev) [inline cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx:574]: How can we get situation when ``activatedStateID !== null``, but it isn't contained in annotations?

Comment (ActiveChooN) [reply cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx:574]: @bsekachev, have no idea but in some situations we have `annotations` with empty list

Comment (bsekachev) [reply cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx:574]: @ActiveChooN 

Probably we should investigate the root cause. It looks like workaround.
At least need to understand the reason

Comment (ActiveChooN) [reply cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx:574]: @bsekachev, i guess we can recreate an issue for further investigation and commit this changes to avoid canvas failing. What do you think?

Comment (bsekachev) [reply cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx:574]: @ActiveChooN 

Yep. Nice way. Could you create it?
