### PR TITLE
React UI: Batch of fixes

### LINKED ISSUE #1413: CVAT new UI: Cancel or tune image shaking while drawing a polygon
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

An image mustn't shake while drawing any shapes.
### Current Behaviour

The left mouse button uses to draw any object and to move an image. It leads to image shaking when we draw some objects, especially polygons.
### Possible Solution

Create another mode to move an image while drawing an object. For example, it can be the mouse wheel or Ctrl+LMB 
### Steps to Reproduce (for bugs)

1. Just try to draw any polygon quickly enough

### Context
It's very uncomfortable for the concentration and for the precisely annotation. Difficult to annotate objects' boundaries.

### LINKED ISSUE #1425: CVAT new UI: The highlighted attribute doesn't correspond to the chosen attribute
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The highlighted attribute in AAM should correspond to the chosen attribute
### Current Behaviour

Noticed that the highlighted with red attribute doesn't correspond to the chosen current attribute on the right panel:
image

### Possible Solution

Fix this mismatch

### Context

It's necessary to have a visual confirmation that we work with the correct attribute.

### LINKED ISSUE #1432: CVAT new ui: annotation uploading fails in annotation window
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Possible Solution

https://github.com/opencv/cvat/blob/develop/cvat-ui/src/actions/annotation-actions.ts#L368-L390

Function is called twice in a row. It expects `history` argument, but in the first call it is not provided, so the call fails with an error, when trying to unpack an input structure. Annotations are uploaded, though.

### Steps to Reproduce (for bugs)

1. Upload annotations in the new UI

### Your Environment

- Git hash commit (`git log -1`): 70b6f0f46c3a0a16d7113e930b71a26b1b105523
- Docker version `docker version` (e.g. Docker 17.0.05): -
- Are you using Docker Swarm or Kubernetes? -
- Operating System and version (e.g. Linux, Windows, MacOS): Unubtu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### LINKED ISSUE #1433: CVAT new UI: bug in "hide" function
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The function "hide" should hide/unhide shapes 
### Current Behaviour

The "hide" function doesn't work. If you click on the corresponding icon or short key the annotated shape won't disappear. But if you grip a shape and move it somewhere it will hide. But you can't unhide it.

### Steps to Reproduce (for bugs)

1. Draw a new shape
1. Press "hide" (H), try to move the shape
1. Try to unhide it

### Context

This function is necessary for lots of annotations scenarios

### LINKED ISSUE #1438: CVAT new UI: cancel "multiple paste" results in a locked workspace
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Workspace is not blocked after cancel "multiple paste".

### Current Behaviour

If you cancel the multiple paste then the workspace is blocked.

### Steps to Reproduce (for bugs)

1. Copy an object using "ctrl + c"
1. Insert an object using "ctrl+v"
1. Hold "ctrl" for multiple paste
1. Insert object (left-click)
1. Do not insert an next object but press "Esc"

### LINKED ISSUE #1439: CVAT new UI: The block with information about the object does not disappear if the object is locked
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

If an object is blocked, a block with information about the object appears when you hover and disappears when you hover over another object. 

### Current Behaviour

If an object is locked, a block with information about the object appears when you hover over it but does not disappear when you hover over another object. Now showing a block with information at a locked object can be called accidentally and a block with information will interfere.

info block lock bug

### Steps to Reproduce (for bugs)

1. Lock object
1. Place the cursor on the object
1. Information block appears
1. Hover over another object
1. The block with information about the object does not disappear

### Context

In workspace
Setting "Always show object details" - disabled

### LINKED ISSUE #1444: CVAT new UI: Filter property "shape" and operator "~="
In the new UI, it’s not clear how to use a filter with the "shape" property, 
I tried the filter "shape == polygon" and the like, but they just hide all the objects.
And also I did not understand in what cases to use the operator "~ =", for example, applying the filter "width ~ = 100" causes an error:

image

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
The PR resolves some issues reported by data annotation and CVAT team:
- Hide functionality (H) doesn't work
- The highlighted attribute doesn't correspond to the chosen attribute in AAM
- Inconvinient image shaking while drawing a polygon (hold Alt key during drawing/editing/grouping to drag an image)
- Filter property "shape" doesn't work and extra operator in description
- Block of text information doesn't disappear after deactivating for locked shapes
- Annotation uploading fails in annotation view
- UI freezes after canceling pasting with escape

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

resolve #1433 
resolve #1425
resolve #1413 (Use Alt key to drag image during drawing/editing/grouping)
resolve #1444
resolve #1439
resolve #1432
resolve #1438

### CODE REVIEW

**Comment by nmanovic** [comment]
@ActiveChooN , could you please review the PR today? As usual it is necessary to install and try to reproduce all issues.

File: cvat-canvas/src/typescript/canvasView.ts [hunk 1]
```diff
@@ -673,7 +668,9 @@ export class CanvasViewImpl implements CanvasView, Listener {
 
         this.content.addEventListener('mousedown', (event): void => {
             if ([1, 2].includes(event.which)) {
-                if (![Mode.ZOOM_CANVAS, Mode.GROUP].includes(this.mode) || event.which === 2) {
+                if ([Mode.IDLE, Mode.DRAG, Mode.MERGE, Mode.SPLIT].includes(this.mode)
+                    || event.which === 2 || event.altKey
+                ) {
```
Comment (ActiveChooN) [inline cvat-canvas/src/typescript/canvasView.ts:673]: Can you change `MouseEvent.wich` to `MouseEvent.buttons` please?
