### PR TITLE
Context menu options for cuboids

### LINKED ISSUE #1499: CVAT new UI: Functions for working with cuboids are missing in the context menu
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The functions "Reset Perspective" and "Switch Orientation" are contained in the context menu.

The functions "Reset Perspective" and "Fit Image" do not work simultaneously.

### Current Behaviour

The functions "Reset Perspective" and "Switch Orientation" are not contained in the context menu. 

“Reset Perspective” is applied by double click, as does “Fit image” - which is inconvenient.

### Possible Solution

Add "reset perspective" and "switch orientation" in the context menu.

“Reset Perspective” is applied by double click with pressing "Shift" or "Ctrl".

### Steps to Reproduce (for bugs)

N/A
### Context

N/A
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

Added cuboid specific options to shape context menu.
Resolve #1499 

изображение

### How has this been tested?

Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-ui/src/utils/math.ts [hunk 1]
```diff
@@ -2,3 +2,13 @@
 export function clamp(value: number, min: number, max: number): number {
     return Math.max(Math.min(value, max), min);
 }
+
+export function shift<T>(array: Array<T>, k: number): Array<T> {
+    if (k > 0) {
+        return array.splice(k).concat(array.slice(0,k));
```
Comment (bsekachev) [inline cvat-ui/src/utils/math.ts:8]: Maybe use slice instead of splice to keep source array immutable?

File: cvat-canvas/src/typescript/svg.patch.ts [hunk 2]
```diff
@@ -944,6 +946,35 @@ function getTopDown(edgeIndex: EdgeIndex): number[] {
...
+                rotate(top, 1);
+                rotate(bot, 1);
+            }else{
+                rotate(top, -1);
+                rotate(bot, -1);
+            }
+            this.cuboidModel.top.points = top;
+            this.cuboidModel.bot.points = bot;
+            this.updateViewAndVM();
+        },
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/svg.patch.ts:976]: Unused code

File: cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx [hunk 3]
```diff
@@ -404,6 +406,53 @@ class ObjectItemContainer extends React.PureComponent<Props> {
...
+        this.resetCuboidPerspective(true);
+
+        objectState.points = shift(objectState.points,
+            orientation(objectState.points) ? 4: -4);
+
+        this.commit();
+    }
+
+    private resetCuboidPerspective = (notCommit?: boolean): void => {
+        function orientation(points: number[]): boolean {
```
Comment (bsekachev) [inline cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx:425]: uninformative name of the function

**Comment by bsekachev** [comment]
Please, update also ``cvat-canvas`` version
And I have a question about reset perspective feature
It seems it doesn't work properly

Peek 2020-05-20 23-00

File: cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx (hunk 3 above)
Comment (ActiveChooN) [reply cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx:425]: @bsekachev, what do you mean? Can you explain with more details?

Comment (bsekachev) [reply cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx:425]: ``if (orientation(points))`` is not very intuitive. What does this function do?

**Comment by bsekachev** [comment]
@ActiveChooN 

Hi, I tried to switch orientation of the same cuboid twice and got: 
```Could not update annotations
Error: Points must have exact 8 points, but got 10
```

And one more question about reset perspective. Is behavior on the gif below expected? 
Peek 2020-06-01 14-49

**Comment by bsekachev** [comment]
@ActiveChooN 

Great. Please, update UI version
