### PR TITLE
Disable submit button while creating GT job

### LINKED ISSUE #7474: Create GT button should be disabled while waiting for GT job creation
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Go to the GT job creation form
1. Fill out the form
1. Press the `create` button 2 times
GT_job_creation_form

### Expected Behavior

_No response_

### Possible Solution

_No response_

### Context

_No response_

### Environment

```Markdown
UI version: 1.61.4
```

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #7474

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: changelog.d/20240229_185536_sekachev.bs_disable_gt_button.md [hunk 1]
```diff
@@ -0,0 +1,4 @@
+### Fixed
+
+- Submit button is enabled while creating a ground truth job
+  (<https://github.com/opencv/cvat/pull/test>)
```
Comment (bsekachev) [inline changelog.d/20240229_185536_sekachev.bs_disable_gt_button.md:4]:
```suggestion
  (<https://github.com/opencv/cvat/pull/7540>)
```

**Review by klakhov — APPROVED** [review]
