### PR TITLE
CVAT UI: batch of fixes

### LINKED ISSUE #1825: Tooltip should be hidden after mouse is out of an element
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

A tooltip should be hidden after mouse is out of an element which generates the tooltip. 

### Current Behaviour

Even I move the mouse cursor out of an element, the tooltip is still visible. It is really annoying problem which doesn't allow in come cases modify/press other UI elements.

image

### Context

I have the problem each time when I try to demonstrate CVAT to internal/external customers. It is a really critical usability issue.

### Your Environment

- Git hash commit (`git log -1`): 

```bash
commit cab375dfc29a4fd1bfefd4405f5092e72ea5efc0 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 6d858407 bb926fc2
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Tue Jun 30 23:07:47 2020 +0300

    Merge branch 'lizhming-develop' into develop
```

- Docker version `docker version` (e.g. Docker 17.0.05): `Docker version 19.03.8, build afacb8b`
- Are you using Docker Swarm or Kubernetes? `No`
- Operating System and version (e.g. Linux, Windows, MacOS): `MacOS`
- Code example or link to GitHub repo or gist to reproduce problem: `N/A`
- Other diagnostic information / logs: `N/A`

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by ActiveChooN**
### Motivation and context

Resolve #1825 
Also resolved few linting isuues

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

File: cvat-ui/src/components/create-model-page/create-model-content.tsx [hunk 1]
```diff
@@ -18,8 +18,8 @@ import ConnectedFileManager, {
 } from 'containers/file-manager/file-manager';
 import { ModelFiles } from 'reducers/interfaces';
 
-import CreateModelForm, {
-    CreateModelForm as WrappedCreateModelForm,
+import WrappedCreateModelForm, {
```
Comment (bsekachev) [inline cvat-ui/src/components/create-model-page/create-model-content.tsx:21]: Default export in this file is not wrapped model form, is a wrapper for model form
