### PR TITLE
Fixed export formats for empty project

### LINKED ISSUE #5381: No export formats are shown for an empty project
If I try to export an empty dataset, I see no available formats for export. I believe it is a bug. Also if I add a task to the project, the list of formats is empty until you update the page.

image

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

- [x] Resolved #5381 
- [x] Fixed warining occured when opening export modal
image
- [x] Fixed ui issue
image

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the documentation accordingly~~
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: tests/cypress/e2e/issues_prs/issue_5381_empty_project_formats.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+const issueId = '5381';
+const project = {
+    name: `Issue ${issueId}`,
+    label: 'Tree',
+    attrName: 'Kind',
+    attrVaue: 'Oak',
+};
+
+context('Check behavior in case of missing authentification data', () => {
```
Comment (bsekachev) [inline tests/cypress/e2e/issues_prs/issue_5381_empty_project_formats.js:15]: authentification data?

File: CHANGELOG.md [hunk 2]
```diff
@@ -24,6 +24,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Invalid mask when running automatic annotation on a task (<https://github.com/opencv/cvat/pull/5883>)
 - Cloud storage content listing when the manifest name contains special characters
   (<https://github.com/opencv/cvat/pull/5873>)
+- Export formats for empty project are not shown (<https://github.com/opencv/cvat/pull/5899>)
```
Comment (bsekachev) [inline CHANGELOG.md:27]:
```suggestion
- Empty list of export formats for a project without tasks (<https://github.com/opencv/cvat/pull/5899>)
```

File: cvat-ui/src/components/export-dataset/export-dataset-modal.tsx [hunk 3]
```diff
@@ -168,10 +170,13 @@ function ExportDatasetModal(props: StateToProps): JSX.Element {
                 >
                     <Select virtual={false} placeholder='Select dataset format' className='cvat-modal-export-select'>
                         {dumpers
-                            .sort((a: any, b: any) => a.name.localeCompare(b.name))
-                            .filter((dumper: any): boolean => dumper.dimension === instance?.dimension)
+                            .sort((a: Dumper, b: Dumper) => a.name.localeCompare(b.name))
+                            .filter(
+                                (dumper: Dumper): boolean => dumper.dimension === instance?.dimension ||
+                                    instance instanceof Project,
```
Comment (bsekachev) [inline cvat-ui/src/components/export-dataset/export-dataset-modal.tsx:176]: Hmm, does this condition work? 
For a project with 3D dimension it will show 2D formats because of the second part ``||  instance instanceof Project``

Comment (bsekachev) [reply cvat-ui/src/components/export-dataset/export-dataset-modal.tsx:176]: Also optional chaining ``?.`` is not necessary here anymore, because all of Job, Task, Project have ``dimension`` property now.

File: cvat-ui/src/components/export-dataset/export-dataset-modal.tsx [hunk 4]
```diff
@@ -56,15 +59,15 @@ function ExportDatasetModal(props: StateToProps): JSX.Element {
         location: StorageLocation.LOCAL,
     });
     const [defaultStorageLocation, setDefaultStorageLocation] = useState(StorageLocation.LOCAL);
-    const [defaultStorageCloudId, setDefaultStorageCloudId] = useState<number | null>(null);
+    const [defaultStorageCloudId, setDefaultStorageCloudId] = useState<number>();
```
Comment (bsekachev) [inline cvat-ui/src/components/export-dataset/export-dataset-modal.tsx:62]: What is a reason to replace ``null`` by ``undefined``?

File: cvat-ui/src/components/export-dataset/export-dataset-modal.tsx (hunk 3 above)
Comment (bsekachev) [reply cvat-ui/src/components/export-dataset/export-dataset-modal.tsx:176]: I see dimension is null for an empty project, so, we probably should check this value.
Like:
```
dumper.dimension === instance.dimension || (instance instanceof Project && instance.dimension === null)
```
What do you think?

image

Comment (klakhov) [reply cvat-ui/src/components/export-dataset/export-dataset-modal.tsx]: Yep, checking for `null` is better.
BTW `istance` can be null, so ?. still needed. (Fixed instance type by adding `| null`)
