### PR TITLE
Fix schema for retrieve_data method (type field)

### LINKED ISSUE #9315: API's data_retrieval not working as explained in the documentation
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. I'm trying to follow the example from https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/tasks-api/#retrieve_data 
2. when I call api_client.tasks_api.retrieve_data(task_id), I get this error message: "HTTP response body: ["Data type not specified or has wrong value"]" . However according to the documentation the only required parameter should be the job ID. I get the same error if I try using api_client.jobs_api.retrieve_data(job_id).

### Expected Behavior

Retrieving the data of the specified task by passing only the task ID if the documentation is right.

If it is wrong then it should be updated.

### Possible Solution

Possibly simply update the doc.

### Context

_No response_

### Environment

```Markdown
- SDK version: 2.32.0
- Server version: 2.32.0
- Python 3.10
```

### PR DESCRIPTION
**Pull request by Grigorii777**
### Motivation and context

Fixes #9315

The OpenAPI schema for `retrieve_data` endpoints (both tasks and jobs) incorrectly marked the `type` query parameter as optional (`required=False`), while the backend validation in `_DataGetter.__init__` actually requires this parameter and raises a `ValidationError` if it's missing or invalid.

This discrepancy caused:
- SDK documentation to show `type` as optional

**Changes:**
- Updated `@extend_schema` decorators for `TaskViewSet.data` to mark `type` parameter as `required=True`
- Updated `@extend_schema` decorators for `JobViewSet.data` to mark `type` parameter as `required=True`
- Created changelog entry documenting the fix

### How has this been tested?

**Manual testing:**
1. Started CVAT locally with Docker Compose
2. Verified that API calls **without** `type` parameter fail with validation error:
   ```bash
   curl -u admin:password "http://localhost:7000/api/tasks/1/data?number=0&quality=compressed"
   # Returns: {"detail": "Data type not specified or has wrong value"}
   ```
3. Verified that API calls with type parameter work correctly:
    ```bash
    curl -u admin:password "http://localhost:7000/api/tasks/1/data?type=chunk&number=0&quality=compressed" --output chunk.zip
    # Successfully downloads chunk
    ```
4. The documentation after merging with develop will be generated correctly.
5. You can also check the work in the examples.
- https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/jobs-api/#example-12
- https://docs.cvat.ai/docs/api_sdk/sdk/reference/apis/tasks-api/#example-15

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] ~~I have updated the documentation accordingly~~
- [ ] ~~I have added tests to cover my changes~~
- [x] I have linked related issues (#9315)

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: changelog.d/20251125_162102_grigorio714_cloud_storage_failed_status_fix.md [hunk 1]
```diff
@@ -1,4 +1,4 @@
 ### Fixed
 
-- Fixed cloud storage status. Unavailable storages now return NOT_FOUND status instead of 400 Bad Request
+- Fixed cloud storage status. Unavailable storages now return NOT_FOUND status instead of 400 Bad Request.
```
Comment (SpecLad) [inline changelog.d/20251125_162102_grigorio714_cloud_storage_failed_status_fix.md]: It's actually a convention here to omit the period at the end of a changelog entry.

Comment (Grigorii777) [reply changelog.d/20251125_162102_grigorio714_cloud_storage_failed_status_fix.md]: Ok, the unit tests just crashed, creating a Docker image, I had to restart it)
I will correct it after the test

Comment (SpecLad) [reply changelog.d/20251125_162102_grigorio714_cloud_storage_failed_status_fix.md]: You can just restart a specific CI job. There's a "re-run jobs" button at the top of the job page.
